site_name: Valiant documentation

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 2.0

nav:
  - Introduction: index.md
#  - Basic Usage: basic-usage.md
#  - Libraries: libraries.md
#  - Commands: cli.md
  - Configuration: configuration.md
#  - Repositories: repositories.md
#  - Managing environments: managing-environments.md
#  - Dependency specification: dependency-specification.md
#  - The pyproject.toml file: pyproject.md
#  - Contributing: contributing.md
#  - FAQ: faq.md
