# Ref:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Default CI workflow
on: [push]

jobs:
  build:
    name: CI tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox>=2020.12.31
          pip install poetry>=1.1.5

      - name: safety
        run: nox -s safety_dev

      - name: bom
        run: nox -s bom

      - name: Upload SBOM
        uses: actions/upload-artifact@master
        with:
          name: bom.json
          path: build/bom.json

      - name: lint
        run: nox -s lint

      - name: mypy
        run: nox -s mypy

      - name: Pytest
        run: |
          nox -s tests-${{ matrix.python-version }} -- \
            --junitxml=junit/test-results-${{ matrix.python-version }}.xml \
            --cov --cov-report xml \
            --cov-report html \
            --cov-report term

      - name: Upload pytest test results
        uses: actions/upload-artifact@master
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit
        if: always()

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: build/reports/coverage
        if: always()

      - name: Build the distribution
        run: poetry build
