# Ref:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Default CI workflow
on: [push]

jobs:
  build:
    name: Default nox tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox>=2019.11.9
        pip install poetry>=1.0.5
        poetry install
    - name: Base nox actions
      run: nox -rs lint safety mypy

    - name: Pytest
      run: nox -s tests -- --junitxml=junit/test-results-${{ matrix.python-version }}.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@master
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: always()

    - name: Coverage report
      run: nox -s coverage_report -- xml -o build/reports/coverage/coverage-${{ matrix.python-version }}.xml

    - name: Upload coverage results
      uses: actions/upload-artifact@master
      with:
        name: coverage-results-${{ matrix.python-version }}
        path: build/reports/coverage/coverage-${{ matrix.python-version }}.xml
