# Ref:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Default CI workflow
on: [push]

jobs:
  build:
    name: CI tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox>=2019.11.9
        pip install poetry>=1.0.5
        poetry install
    - name: Base nox actions
      run: nox -rs lint safety mypy

    - name: Pytest
      run: |
        nox -rs tests -- \
          --junitxml=junit/test-results-${{ matrix.python-version }}.xml \
          --cov --cov-report xml:build/reports/coverage/${{ matrix.python-version }}.xml \
          --cov-report html:build/reports/coverage/html/${{ matrix.python-version }} \
          --cov-report term

    - name: Upload pytest test results
      uses: actions/upload-artifact@master
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit
      if: always()

    - name: Upload coverage results
      uses: actions/upload-artifact@master
      with:
        name: coverage-results-${{ matrix.python-version }}
        path: build/reports/coverage
      if: always()

    - name: Build the distribution
      run: poetry build

    #- name: Archive build artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: dist
    #    path: dist
